
trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: branchPath
    value: $(Build.SourceBranch)

steps:
- script: yarn install
  displayName: Installing npm packages
- script: yarn run dist
  displayName: 'Build dist version of library'

- script: |
    declare -x PACKAGE_VERSION=${$(branchPath):11}
    echo $PACKAGE_VERSION
    cd ./dist/ngx-autofocus-directive
    apt-get install sed
    "sed -i \"s/\\\"version\\\": .*,/\\\"version\\\": \\\"${PACKAGE_VERSION}\\\",/g\" \"package.json\""
  displayName: 'Publish to npm registry'
