
trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: branchPath
    value: $(Build.SourceBranch)

steps:
- script: yarn install
  displayName: Installing npm packages
- script: yarn run dist
  displayName: 'Build dist version of library'

- script: |
    TAG_PATH="$(branchPath)"
    PACKAGE_VERSION=${TAG_PATH:11}
    echo "version: $PACKAGE_VERSION"
    sed -i "s/\"version\": .*,/\"version\": \"${PACKAGE_VERSION}\",/g" package.json
  displayName: 'Publish to npm registry'
  workingDirectory: dist/ngx-autofocus-directive
