
trigger:
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: tagName
    value: $(Build.BuildId)

steps:
- script: yarn install
  displayName: Installing npm packages
- script: yarn run dist
  displayName: 'Build dist version of library'

- script: echo $(tagName)

